In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
csv_path = "Source_File/Average_income_file_nj.csv"
NJ_Avg_income_df = pd.read_csv(csv_path)

NJ_Avg_income_df.head()

,FIPS,State,Area_name,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Median_Household_Income_2013,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployment_rate_2016,Median_Household_Income_2016,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Median_Household_Income_2017,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018
0,34000,NJ,New Jersey,"4,173,828","374,732",8.2,"$1,396,011.00","4,183,541","303,497",6.8,...,5.0,"$1,475,455.00",4247535,205990,4.6,"$1,529,652.00","4,239,567","183,375",4.1,"$1,606,570.00"
1,34001,NJ,"Atlantic County, NJ","121,628","16,079",11.7,"$41,664.00","117,879","13,907",10.6,...,7.4,"$44,053.00",110060,8562,7.2,"$44,771.00","111,968","7,001",5.9,"$46,557.00"
2,34003,NJ,"Bergen County, NJ","449,009","32,389",6.7,"$79,037.00","451,477","25,982",5.4,...,4.2,"$84,309.00",456948,18500,3.9,"$88,512.00","455,773","16,228",3.4,"$93,205.00"
3,34005,NJ,"Burlington County, NJ","215,038","17,917",7.7,"$74,285.00","213,837","14,693",6.4,...,4.5,"$74,844.00",220764,9410,4.1,"$80,081.00","218,877","8,568",3.8,"$86,777.00"
4,34007,NJ,"Camden County, NJ","233,809","24,261",9.4,"$58,572.00","232,309","19,401",7.7,...,5.5,"$63,589.00",240342,12875,5.1,"$65,838.00","238,357","11,588",4.6,"$65,817.00"

In [3]:
NJ_Avg_income_df.count()

FIPS                            22
State                           22
Area_name                       22
 Employed_2013                  22
 Unemployed_2013                22
Unemployment_rate_2013          22
Median_Household_Income_2013    22
 Employed_2014                  22
 Unemployed_2014                22
Unemployment_rate_2014          22
Median_Household_Income_2014    22
 Employed_2015                  22
 Unemployed_2015                22
Unemployment_rate_2015          22
Median_Household_Income_2015    22
 Employed_2016                  22
 Unemployed_2016                22
Unemployment_rate_2016          22
Median_Household_Income_2016    22
Employed_2017                   22
Unemployed_2017                 22
Unemployment_rate_2017          22
Median_Household_Income_2017    22
Employed_2018                   22
Unemployed_2018                 22
Unemployment_rate_2018          22
Median_Household_Income_2018    22
dtype: int64

In [4]:
NJ_Avg_income_df = NJ_Avg_income_df.rename(columns={"State": "State_Id", "Area_name": "County_Name", "Median_Household_Income_2013": "Avg_income_2013", 
                                                          "Median_Household_Income_2014": "Avg_income_2014", "Median_Household_Income_2015": "Avg_income_2015", 
                                                          "Median_Household_Income_2016": "Avg_income_2016", "Median_Household_Income_2017": "Avg_income_2017",
                                                          "Median_Household_Income_2018": "Avg_income_2018"})
NJ_Avg_income_df.head()

,FIPS,State_Id,County_Name,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Avg_income_2013,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployment_rate_2016,Avg_income_2016,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Avg_income_2017,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Avg_income_2018
0,34000,NJ,New Jersey,"4,173,828","374,732",8.2,"$1,396,011.00","4,183,541","303,497",6.8,...,5.0,"$1,475,455.00",4247535,205990,4.6,"$1,529,652.00","4,239,567","183,375",4.1,"$1,606,570.00"
1,34001,NJ,"Atlantic County, NJ","121,628","16,079",11.7,"$41,664.00","117,879","13,907",10.6,...,7.4,"$44,053.00",110060,8562,7.2,"$44,771.00","111,968","7,001",5.9,"$46,557.00"
2,34003,NJ,"Bergen County, NJ","449,009","32,389",6.7,"$79,037.00","451,477","25,982",5.4,...,4.2,"$84,309.00",456948,18500,3.9,"$88,512.00","455,773","16,228",3.4,"$93,205.00"
3,34005,NJ,"Burlington County, NJ","215,038","17,917",7.7,"$74,285.00","213,837","14,693",6.4,...,4.5,"$74,844.00",220764,9410,4.1,"$80,081.00","218,877","8,568",3.8,"$86,777.00"
4,34007,NJ,"Camden County, NJ","233,809","24,261",9.4,"$58,572.00","232,309","19,401",7.7,...,5.5,"$63,589.00",240342,12875,5.1,"$65,838.00","238,357","11,588",4.6,"$65,817.00"

In [5]:
NJ_Avg_income_df.columns

Index(['FIPS', 'State_Id', 'County_Name', ' Employed_2013', ' Unemployed_2013',
       'Unemployment_rate_2013', 'Avg_income_2013', ' Employed_2014',
       ' Unemployed_2014', 'Unemployment_rate_2014', 'Avg_income_2014',
       ' Employed_2015', ' Unemployed_2015', 'Unemployment_rate_2015',
       'Avg_income_2015', ' Employed_2016', ' Unemployed_2016',
       'Unemployment_rate_2016', 'Avg_income_2016', 'Employed_2017',
       'Unemployed_2017', 'Unemployment_rate_2017', 'Avg_income_2017',
       'Employed_2018', 'Unemployed_2018', 'Unemployment_rate_2018',
       'Avg_income_2018'],
      dtype='object')

In [6]:
NJ_Avg_income_df = NJ_Avg_income_df.drop (["FIPS"," Employed_2013"," Unemployed_2013"," Employed_2014"," Unemployed_2014",
                        " Employed_2015"," Unemployed_2015"," Employed_2016"," Unemployed_2016",
                        "Employed_2017","Unemployed_2017", "Employed_2018","Unemployed_2018"],axis = 1)
NJ_Avg_income_df.head()

,State_Id,County_Name,Unemployment_rate_2013,Avg_income_2013,Unemployment_rate_2014,Avg_income_2014,Unemployment_rate_2015,Avg_income_2015,Unemployment_rate_2016,Avg_income_2016,Unemployment_rate_2017,Avg_income_2017,Unemployment_rate_2018,Avg_income_2018
0,NJ,New Jersey,8.2,"$1,396,011.00",6.8,"$1,419,167.00",5.8,"$1,456,315.00",5.0,"$1,475,455.00",4.6,"$1,529,652.00",4.1,"$1,606,570.00"
1,NJ,"Atlantic County, NJ",11.7,"$41,664.00",10.6,"$42,201.00",9.6,"$43,244.00",7.4,"$44,053.00",7.2,"$44,771.00",5.9,"$46,557.00"
2,NJ,"Bergen County, NJ",6.7,"$79,037.00",5.4,"$82,001.00",4.7,"$81,615.00",4.2,"$84,309.00",3.9,"$88,512.00",3.4,"$93,205.00"
3,NJ,"Burlington County, NJ",7.7,"$74,285.00",6.4,"$76,868.00",5.3,"$80,479.00",4.5,"$74,844.00",4.1,"$80,081.00",3.8,"$86,777.00"
4,NJ,"Camden County, NJ",9.4,"$58,572.00",7.7,"$57,641.00",6.5,"$61,685.00",5.5,"$63,589.00",5.1,"$65,838.00",4.6,"$65,817.00"

In [11]:
NJ_Avg_income_df=NJ_Avg_income_df[NJ_Avg_income_df.County_Name !='New Jersey']
NJ_Avg_income_df.head()

,State_Id,County_Name,Unemployment_rate_2013,Avg_income_2013,Unemployment_rate_2014,Avg_income_2014,Unemployment_rate_2015,Avg_income_2015,Unemployment_rate_2016,Avg_income_2016,Unemployment_rate_2017,Avg_income_2017,Unemployment_rate_2018,Avg_income_2018
1,NJ,"Atlantic County, NJ",11.7,"$41,664.00",10.6,"$42,201.00",9.6,"$43,244.00",7.4,"$44,053.00",7.2,"$44,771.00",5.9,"$46,557.00"
2,NJ,"Bergen County, NJ",6.7,"$79,037.00",5.4,"$82,001.00",4.7,"$81,615.00",4.2,"$84,309.00",3.9,"$88,512.00",3.4,"$93,205.00"
3,NJ,"Burlington County, NJ",7.7,"$74,285.00",6.4,"$76,868.00",5.3,"$80,479.00",4.5,"$74,844.00",4.1,"$80,081.00",3.8,"$86,777.00"
4,NJ,"Camden County, NJ",9.4,"$58,572.00",7.7,"$57,641.00",6.5,"$61,685.00",5.5,"$63,589.00",5.1,"$65,838.00",4.6,"$65,817.00"
5,NJ,"Cape May County, NJ",14.3,"$48,691.00",12.2,"$49,443.00",11.1,"$51,322.00",9.8,"$53,981.00",9.2,"$55,875.00",8.4,"$58,324.00"

In [12]:
NJ_Avg_income_df.columns=NJ_Avg_income_df.columns.str.replace('County, NJ','County')

In [15]:
NJ_Avg_income_df['County_Name'] = NJ_Avg_income_df['County_Name'].str.split(",", n=1,expand=True)

In [16]:
NJ_Avg_income_df

,State_Id,County_Name,Unemployment_rate_2013,Avg_income_2013,Unemployment_rate_2014,Avg_income_2014,Unemployment_rate_2015,Avg_income_2015,Unemployment_rate_2016,Avg_income_2016,Unemployment_rate_2017,Avg_income_2017,Unemployment_rate_2018,Avg_income_2018
1,NJ,Atlantic County,11.7,"$41,664.00",10.6,"$42,201.00",9.6,"$43,244.00",7.4,"$44,053.00",7.2,"$44,771.00",5.9,"$46,557.00"
2,NJ,Bergen County,6.7,"$79,037.00",5.4,"$82,001.00",4.7,"$81,615.00",4.2,"$84,309.00",3.9,"$88,512.00",3.4,"$93,205.00"
3,NJ,Burlington County,7.7,"$74,285.00",6.4,"$76,868.00",5.3,"$80,479.00",4.5,"$74,844.00",4.1,"$80,081.00",3.8,"$86,777.00"
4,NJ,Camden County,9.4,"$58,572.00",7.7,"$57,641.00",6.5,"$61,685.00",5.5,"$63,589.00",5.1,"$65,838.00",4.6,"$65,817.00"
5,NJ,Cape May County,14.3,"$48,691.00",12.2,"$49,443.00",11.1,"$51,322.00",9.8,"$53,981.00",9.2,"$55,875.00",8.4,"$58,324.00"
6,NJ,Cumberland County,11.7,"$34,109.00",9.9,"$34,349.00",8.8,"$35,366.00",7.5,"$36,814.00",7.0,"$37,408.00",6.5,"$38,893.00"
7,NJ,Essex County,9.7,"$54,783.00",8.0,"$55,369.00",6.9,"$57,817.00",6.0,"$60,131.00",5.7,"$61,287.00",5.2,"$63,554.00"
8,NJ,Gloucester County,9.0,"$44,895.00",7.3,"$45,826.00",6.1,"$47,305.00",5.1,"$49,636.00",4.7,"$50,589.00",4.2,"$52,506.00"
9,NJ,Hudson County,7.9,"$47,628.00",6.4,"$48,344.00",5.4,"$51,776.00",4.7,"$55,354.00",4.4,"$57,081.00",3.9,"$59,623.00"
10,NJ,Hunterdon County,5.9,"$103,301.00",4.9,"$107,203.00",4.3,"$103,876.00",3.8,"$102,797.00",3.5,"$113,336.00",3.3,"$113,083.00"
11,NJ,Mercer County,7.3,"$67,662.00",5.9,"$70,575.00",5.0,"$73,750.00",4.4,"$72,172.00",4.1,"$76,988.00",3.7,"$78,161.00"
12,NJ,Middlesex County,7.5,"$77,044.00",6.1,"$76,515.00",5.2,"$77,330.00",4.4,"$78,249.00",4.1,"$82,183.00",3.6,"$85,187.00"
13,NJ,Monmouth County,7.5,"$81,190.00",6.1,"$83,424.00",5.2,"$87,220.00",4.5,"$86,722.00",4.1,"$89,968.00",3.7,"$97,627.00"
14,NJ,Morris County,6.2,"$95,236.00",5.0,"$99,950.00",4.4,"$100,511.00",3.9,"$101,754.00",3.6,"$107,019.00",3.3,"$114,269.00"
15,NJ,Ocean County,9.3,"$59,022.00",7.4,"$59,888.00",6.2,"$62,937.00",5.2,"$63,478.00",4.8,"$62,276.00",4.3,"$70,493.00"
16,NJ,Passaic County,10.0,"$58,073.00",8.3,"$57,426.00",7.1,"$58,030.00",6.2,"$55,723.00",5.7,"$61,517.00",5.1,"$63,127.00"
17,NJ,Salem County,10.4,"$57,939.00",8.5,"$58,483.00",7.3,"$56,645.00",6.4,"$63,988.00",6.2,"$56,071.00",5.4,"$61,322.00"
18,NJ,Somerset County,6.3,"$95,574.00",5.2,"$96,947.00",4.6,"$100,194.00",4.1,"$99,059.00",3.8,"$104,668.00",3.4,"$111,838.00"
19,NJ,Sussex County,7.9,"$82,048.00",6.4,"$84,431.00",5.5,"$85,747.00",4.7,"$86,549.00",4.4,"$87,549.00",4.0,"$89,744.00"
20,NJ,Union County,8.4,"$64,698.00",7.0,"$64,272.00",6.1,"$68,172.00",5.2,"$70,581.00",4.8,"$71,801.00",4.3,"$76,830.00"
21,NJ,Warren County,7.6,"$70,560.00",6.3,"$68,011.00",5.4,"$71,294.00",4.6,"$71,672.00",4.2,"$74,834.00",3.8,"$79,633.00"