In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [6]:
# Import Avrage income by county and years (2013 -2018) for state of NJ   
csv_path = "Source_File/Average_income_file_nj.csv"
NJ_Avg_income_df = pd.read_csv(csv_path)

NJ_Avg_income_df.head()

,FIPS,State,Area_name,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Median_Household_Income_2013,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployment_rate_2016,Median_Household_Income_2016,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Median_Household_Income_2017,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018
0,34000,NJ,New Jersey,"4,173,828","374,732",8.2,"$1,396,011.00","4,183,541","303,497",6.8,...,5.0,"$1,475,455.00",4247535,205990,4.6,"$1,529,652.00","4,239,567","183,375",4.1,"$1,606,570.00"
1,34001,NJ,"Atlantic County, NJ","121,628","16,079",11.7,"$41,664.00","117,879","13,907",10.6,...,7.4,"$44,053.00",110060,8562,7.2,"$44,771.00","111,968","7,001",5.9,"$46,557.00"
2,34003,NJ,"Bergen County, NJ","449,009","32,389",6.7,"$79,037.00","451,477","25,982",5.4,...,4.2,"$84,309.00",456948,18500,3.9,"$88,512.00","455,773","16,228",3.4,"$93,205.00"
3,34005,NJ,"Burlington County, NJ","215,038","17,917",7.7,"$74,285.00","213,837","14,693",6.4,...,4.5,"$74,844.00",220764,9410,4.1,"$80,081.00","218,877","8,568",3.8,"$86,777.00"
4,34007,NJ,"Camden County, NJ","233,809","24,261",9.4,"$58,572.00","232,309","19,401",7.7,...,5.5,"$63,589.00",240342,12875,5.1,"$65,838.00","238,357","11,588",4.6,"$65,817.00"

In [ ]:
NJ_Avg_income_df.count()

In [ ]:
# Renaming of data variables 
NJ_Avg_income_df = NJ_Avg_income_df.rename(columns={"State": "State_Id", "Area_name": "County_Name", "Median_Household_Income_2013": "Avg_income_2013", 
                                                          "Median_Household_Income_2014": "Avg_income_2014", "Median_Household_Income_2015": "Avg_income_2015", 
                                                          "Median_Household_Income_2016": "Avg_income_2016", "Median_Household_Income_2017": "Avg_income_2017",
                                                          "Median_Household_Income_2018": "Avg_income_2018"})
NJ_Avg_income_df.head()

In [ ]:
NJ_Avg_income_df.columns

In [ ]:
#Drop variabls that are not required for analysis
NJ_Avg_income_df = NJ_Avg_income_df.drop (["FIPS"," Employed_2013"," Unemployed_2013"," Employed_2014"," Unemployed_2014",
                        " Employed_2015"," Unemployed_2015"," Employed_2016"," Unemployed_2016",
                        "Employed_2017","Unemployed_2017", "Employed_2018","Unemployed_2018"],axis = 1)
NJ_Avg_income_df.head()

In [ ]:
# Data Clean Up Step 1
# Removing total count for NJ State andretainf only county levle counts
NJ_Avg_income_df=NJ_Avg_income_df[NJ_Avg_income_df.County_Name !='New Jersey']
NJ_Avg_income_df.head()

In [ ]:
# Data Clean Up Step 2
# Removing "," and "NJ" stings from the data variable to retain only County name.
NJ_Avg_income_df.columns=NJ_Avg_income_df.columns.str.replace('County, NJ','County')

In [ ]:
NJ_Avg_income_df['County_Name'] = NJ_Avg_income_df['County_Name'].str.split(",", n=1,expand=True)

In [ ]:
NJ_Avg_income_df

In [ ]:
#Drop variabls that are not required for analysis
NJ_Avg_income_df=NJ_Avg_income_df.drop(["Unemployment_rate_2013","Unemployment_rate_2014",
                                                              "Unemployment_rate_2015","Unemployment_rate_2016",
                                                              "Unemployment_rate_2017","Unemployment_rate_2018",],axis = 1)
NJ_Avg_income_df.head()

In [ ]:
NJ_Avg_income_df.columns

In [ ]:
# Create Line Graph to show average Income per count by each year.
NJ_Avg_income_df = NJ_Avg_income_df
County = ['County_Name']
Year = [0, 150000]
plt.plot (County, Year)
Plt.plot(kind='line')
plt.title('Average Income By County Per Year')
plt.ylabel('Years 2013 - 2018')
plt.xlabel('Counties Of New Jersey')
plt.show()

In [ ]:
#Export the graph to local drive